export const FETCH_MAP_STATE_REQUEST = 'FETCH_MAP_STATE_REQUEST';
export const FETCH_MAP_STATE_SUCCESS = 'FETCH_MAP_STATE_SUCCESS';
export const FETCH_MAP_STATE_ERROR = 'FETCH_MAP_STATE_ERROR';


export const FETCH_ROUTES = 'FETCH_ROUTES';
export const FETCH_FLIGHTS = 'FETCH_FLIGHTS';
export const UPDATE_FLIGHTS = 'UPDATE_FLIGHTS';

